version: 2.1

orbs:
  maven: circleci/maven@1.1.0

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          executor:
            name: maven/default
            tag: "11.0"

